### ISSUE TITLE
Not Killing Devices

### ISSUE THREAD

**Issue by h3llH0undX** [elmoiv/elmocut#10]
I have installed NpCap and followed all instructions but it's not working for me at all.

**Comment by elmoiv** [comment]
Can you provide some information to help solving your issue:

- Your Windows version and build.
- Your adapter brand and any info related about it.
- Are you connecting to router via Ethernet Cable or Wi-Fi?
- Do you have more than one adapter connecting to internet at the same time?

**Comment by h3llH0undX** [comment]
Windows 10
TP-Link, StormFiber
Wifi
NO

**Comment by elmoiv** [comment]
Are you connecting to Wi-Fi extender.

In case you are connecting to Wi-Fi extender and not directly to Router, this may cause some issues with elmoCut as it can't operate well in Layer 2

**Comment by h3llH0undX** [comment]
No, i'm connecting to main router

**Comment by elmoiv** [comment]
Can you try NetCut and see if it kills devices or not.

- If worked correctly, I will send you a patched version of elmoCut to produce a config log about your device.
- If not, then the problem may be with your router (may be using EAP-TLS or has a Management Frame Protection). In this situation you can only solve this issue by re-configuring your router to a normal settings.

**Comment by h3llH0undX** [comment]
yes netCut is working

**Comment by h3llH0undX** [comment]
Ok after this last update i reinstalled and it's working now Thanks

**Comment by elmoiv** [comment]
- Please download the following:
https://github.com/elmoiv/elmocut/raw/main/data/Qt5WinExtras.dll
https://github.com/elmoiv/elmocut/raw/main/data/elmoCut.exe
- Put them in elmoCut application folder
- Run elmoCut.exe: This will create a log file called `elmocut_info.log`

Please send me a copy of this log.

- You can also try to kill a device and report if it's still not working.

*Note that this log will contain the names of WiFi networks you previously connected to. So feel free to remove them from the file.*

**Comment by elmoiv** [comment]
issue closed due to inactivity. Feel free to re-open it if you have any updates :)
