### ISSUE TITLE
Not Detecting Any Users

### ISSUE THREAD

**Issue by Djalil62** [elmoiv/elmocut#11]
Hello agian.
im trying to detect internet users but nothing showing only my pc + when i do a settings change and press apply the programe quite !
and thanks

**Comment by elmoiv** [comment]
I will try to find a solution after my finishing my exams. 2 weeks left :)

**Comment by Djalil62** [comment]
well goodluck

**Comment by elmoiv** [comment]
Could you please attach a screenshot of elmoCut running?

**Comment by Djalil62** [comment]
nvm bro i fixed it

**Comment by elmoiv** [comment]
Please describe here the problem and how did you fix it in case anyone has the same issue like you.

**Comment by Djalil62** [comment]
my network adapter wast to old
i bought new adapter and worked perfectly

**Comment by elmoiv** [comment]
Thanks for your help :)
