### ISSUE TITLE
Fatal error detected --> Failed to execute script elmocut

### ISSUE THREAD

**Issue by steveid53** [elmoiv/elmocut#12]
I have two systems: Desktop computer w/ latest updated version of Windows 10, and Laptop computer with the same. ElmoCut installs and runs fine on the desktop, but on the laptop it fails in the same way previously described by GuessJuice in Issue #2: Fatal error detected --> Failed to execute script elmocut

I tried replacing my elmocut.exe with your patched version...
[https://github.com/elmoiv/elmocut/blob/38efa1c6f55d0beb55907fda16f4a731109b682c/data/elmocut.exe?raw=true](https://github.com/elmoiv/elmocut/blob/38efa1c6f55d0beb55907fda16f4a731109b682c/data/elmocut.exe?raw=true)
Then I no longer get the error message, but a window briefly pops up with "C:\Program Files (x86)\elmoCut\elmocut.exe", and then nothing.

Thank you kindly for any advice...8-)

**Comment by elmoiv** [comment]
Which version of elmocut you are using?

**Comment by steveid53** [comment]
elmoCut.1.0.4.x64.exe

**Comment by steveid53** [comment]
These is no folder called elmocut in C:\Users\%username%\Documents

**Comment by elmoiv** [comment]
I guess you have the same #6 issue.
Try the solution and confirm if it's solved.

**Comment by steveid53** [comment]
Controlled Folder Access was already turned off in Manage Ransomware Protection, but the problem persists. Confirmed my Windows 10 version is up to date as of today.

**Comment by elmoiv** [comment]
- Please download the following:
  - https://github.com/elmoiv/elmocut/raw/main/data/Qt5WinExtras.dll
  - https://github.com/elmoiv/elmocut/blob/50661f629435fd2ea169a002c11ab7067c18f931/data/elmoCut.exe?raw=true
  - https://github.com/elmoiv/elmocut/blob/main/data/QtWinExtras.pyd?raw=true
- Move `Qt5WinExtras.dll` and `elmoCut.exe`  to elmoCut root folder.
- Move `QtWinExtras.pyd` to `elmoCut\\PyQt5`.
- In elmoCut root folder hold Shift key then right click and select _(Open PowerShell window here)_
- Now write this in the PowerShell: `./elmocut`
- This will show you a log of what happens before the error.

Please send me a copy of what you've got.

**Comment by steveid53** [comment]
PS C:\Program Files (x86)\elmoCut> ./elmocut
Traceback (most recent call last):
  File "elmoCut.py", line 2, in <module>
ImportError: DLL load failed: The specified module could not be found.
[6808] Failed to execute script elmoCut

**Comment by elmoiv** [comment]
This is really weird :/
The only thing I can think of is that your laptop may not has visual studio redistributable 2015 Installed:
Try Installing both x64 and x86 bit versions from here:
- https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe
- https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

**Comment by steveid53** [comment]
I uninstalled all versions of Visual C: 2005, 2008, 2010, 2013, and 2015. Then I reinstalled 2015 x64 and x86 from your microsoft links, and finally reinstalled elmocut. But unfortunately I'm still getting the same error.

**Comment by elmoiv** [comment]
At this point I can't do much to help :(

The next version will have some fixes. Wait for the release and try.

If the same problem still exists, you may try alternative arp spoofing software untill this issue is solved in the future :/

**Comment by steveid53** [comment]
Ok look forward to your next release. Thank you for your kind assistance...8-)

**Comment by elmoiv** [comment]
> PS C:\Program Files (x86)\elmoCut> ./elmocut
> Traceback (most recent call last):
> File "elmoCut.py", line 2, in
> ImportError: DLL load failed: The specified module could not be found.
> [6808] Failed to execute script elmoCut

Can you try the new release and give me a feedback?
https://github.com/elmoiv/elmocut/releases/tag/1.0.5

**Comment by steveid53** [comment]
I installed your new version elmoCut.1.0.5.x64.exe on both my systems and am happy to report that this issue has been resolved. Thank you Khaled!
