### ISSUE TITLE
Fatal error detected --> Failed to execute script elmocut 

### ISSUE THREAD

**Issue by h3llH0undX** [elmoiv/elmocut#13]

**Comment by elmoiv** [comment]
- Please download the following:
  - https://github.com/elmoiv/elmocut/raw/main/data/Qt5WinExtras.dll
  - https://github.com/elmoiv/elmocut/blob/50661f629435fd2ea169a002c11ab7067c18f931/data/elmoCut.exe?raw=true
  - https://github.com/elmoiv/elmocut/blob/main/data/QtWinExtras.pyd?raw=true
- Move `Qt5WinExtras.dll` and `elmoCut.exe`  to elmoCut root folder.
- Move `QtWinExtras.pyd` to `elmoCut\\PyQt5`.
- In elmoCut root folder hold Shift key then right click and select _(Open PowerShell window here)_
- Now write this in the PowerShell: `./elmocut`
- This will show you a log of what happens before the error.

Please send me a copy of what you've got.


If the previous method is not working for you, please wait for the next version (will be available soon) that may fix your bug.
