### ISSUE TITLE
Killing Connection Not Working

### ISSUE THREAD

**Issue by h3llH0undX** [elmoiv/elmocut#14]
Device in killed list 
Connection show limited but internet still works idk what's  the problem

![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/54775964/125790603-f3f33978-9af8-431c-b184-918de3696869.jpg)

**Comment by elmoiv** [comment]
Couldn't you reply first to issue #13 opened by you.

Please attach how did you solve the fatal error message, close the issue and come here to see if I can help you with your network problem.

**Comment by elmoiv** [comment]
Issue closed due to inactivity.

Feel free to re-open it if your issue still exists.
