### ISSUE TITLE
Failed to execute script elmocut

### ISSUE THREAD

**Issue by apochi2** [elmoiv/elmocut#15]
Traceback (most recent call last):
  File "elmocut.py", line 2, in <module>
ImportError: DLL load failed: The specified module could not be found.
[12280] Failed to execute script elmocut

**Comment by elmoiv** [comment]
What version of windows you're using?

**Comment by apochi2** [comment]
Windows 10 Home latest version

**Comment by apochi2** [comment]
I have both x86 and x64 Visual C++ 2015 installed

**Comment by apochi2** [comment]
I'm using Avast Antivirus

**Comment by elmoiv** [comment]
@apochi2 
Can you try the new release and give me a feedback?
https://github.com/elmoiv/elmocut/releases/tag/1.0.5

**Comment by elmoiv** [comment]
Issue closed due to inactivity.

Feel free to re-open it if your issue still exists
