### ISSUE TITLE
Elmocut is not detecting any other device other than my own PC.

### ISSUE THREAD

**Issue by TTrinxx** [elmoiv/elmocut#16]
The software does not detect any other device other than my router and my PC.
I followed the instructions and installed Npcap as well.

**Desktop**
 - OS: Windows 10 Pro
 - Latest version
 - Avast Antivirus

I can confirm there is at least 3 phones connected to my wireless network - and all of them are functional and show up with their MAC address in my router information/dashboard.

I tried restarting my PC, reinstalling both Npcap & Elmocut, executing as admin, different network interfaces and rescans.
Here is a screenshot of what I can see:
![SCANRESULTS](https://user-images.githubusercontent.com/88005864/127062483-082b189c-ae77-47da-ae62-5a60ac1fc632.png)

**Comment by elmoiv** [comment]
If this is version 1.0.5 
please try version 1.0.4 and reply with any feedback

**Comment by TTrinxx** [comment]
I got Elmocut since yesterday, and I only updated to 1.5 today -- I was hoping it would fix the issue, but sadly it didn't...
So, I had the issue on both 1.0.4 and 1.0.5 today.

**Comment by elmoiv** [comment]
I will try to see if I can fix this issue. I will send you some tests tomorrow to examine this bug.

**Comment by elmoiv** [comment]
Can you send me the output of the following commands:

- `arp -a`
- `netsh interface ip show address`
- `ipconfig | findstr /i gateway`

**Comment by TTrinxx** [comment]
![ARP](https://user-images.githubusercontent.com/88005864/127158150-f00e95e2-b824-4b8d-8ea4-686572a75d74.png)
![netsh](https://user-images.githubusercontent.com/88005864/127158171-83737667-433f-4b07-bb1e-dca985307e3d.png)
![gateway](https://user-images.githubusercontent.com/88005864/127158182-b1fcfc64-4b08-4a33-b105-fd3c4bb89d8b.png)

**Comment by elmoiv** [comment]
Thanks for your feedback.

Change your system language to English and try again.

**Comment by TTrinxx** [comment]
Wow, it was something really this simple... now I'm able to see every device.

Is this normal? I would've expected to see this in the "limitations" part of the wiki - but in any case, it works perfectly fine now, thank you.

**Comment by elmoiv** [comment]
I will edit the limitations part till I find a way to make it work for all languages.

Sorry for the inconvenience :(
