### ISSUE TITLE
base_library.zip error, "out of memory"

### ISSUE THREAD

**Issue by Keramis** [elmoiv/elmocut#17]
OS: Windows 10 Home, Version	10.0.19043 Build 19043
Processor	AMD Ryzen 5 3600 6-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB
Available Physical Memory	21.1 GB
GPU:	NVIDIA GeForce GTX 1660 SUPER

Summary of the issue:
Any install, on my user or on all users, with or without the desktop shortcut, reproduces this message without fail:
![image](https://user-images.githubusercontent.com/81401952/136644451-e59a1f66-e1bd-4029-ab8e-7e0172a4bf9c.png)
I have no clue why this happens, please help.

**Comment by elmoiv** [comment]
You can now download the SFX version of elmoCut to solve this issue.

https://github.com/elmoiv/elmocut/issues/20

**Comment by minanapil13** [comment]
The same here idont know the error

**Comment by minanapil13** [comment]
The same errror what i can do for it i traied many versions of windows it setup first but when i do the programe for multimedia installations it's happen i think its a installatio issues
