### ISSUE TITLE
Error during Install ..

### ISSUE THREAD

**Issue by TareqAbAmawi** [elmoiv/elmocut#19]
https://i.ibb.co/q0kXXR9/2021-11-06-01-28-53-Setup-elmo-Cut-version-1-0-5.png

not only this file ... all files same errors .

**Comment by elmoiv** [comment]
This seems to be the same as #17 ,

> This is really weird :/
> 
> Try the following:
> 
> Run The Installer as Admin.
> Increase your Virtual Memory
>
> If this didn't help, Try to install it on another PC and copy the contents to yours.

**Comment by elmoiv** [comment]
You can now download the SFX version of elmoCut to solve this issue.

#20
