### ISSUE TITLE
Out of memory Error

### ISSUE THREAD

**Issue by Helpme0822** [elmoiv/elmocut#20]
When I try to install the program I get for almost every file an error saying "An error occurred while trying to copy a file : Out of memory." I saw your comment in the other issue about trying to run the installer as admin and about trying to extend the virtual memory but both of these solutions didn't work so do you maybe know any other solution?

**Comment by elmoiv** [comment]
I've uploaded a SFX version of the installer. Download it from here:
https://github.com/elmoiv/elmocut/releases/download/1.0.5/elmoCut.1.0.5.x64.SFX.exe

Try it and confirm if your problem is solved.

Note that this will not add a shortcut of elmoCut to your desktop.

**Comment by Helpme0822** [comment]
Thanks that worked for me.

But where is the option to limit the download speed of a device?

**Comment by elmoiv** [comment]
This option is not implemented yet. It may be available in the upcoming updates.
