### ISSUE TITLE
Disconnects All

### ISSUE THREAD

**Issue by Kingy0100** [elmoiv/elmocut#21]
When using elmocut by killing one ip it will kill all any help on this?
thanks.

**Comment by elmoiv** [comment]
This issue may be related to your Router or your WiFi driver.

Try to use different Interface from settings if you have extra WiFi interface (e.g. external dongle)

**Comment by Kingy0100** [comment]
No problem thank you must be an issue with the laptop I'm using I think.On Dec 11, 2021 7:10 AM, Khaled ElMorshedy ***@***.***> wrote:
This issue may be related to your Router or your WiFi driver.
Try to use different Interface from settings if you have extra WiFi interface (e.g. external dongle)
