### ISSUE TITLE
[Suggestion] Add name to devices

### ISSUE THREAD

**Issue by LuanHimmlisch** [elmoiv/elmocut#22]
Since it's difficult to remember all the IPs of the devices it would be nice to add a nickname to each device that can be stored accordingly to the MAC Address, so if the IP changes you still have a track on them

**Comment by elmoiv** [comment]
Sounds like a handy feature.

I will try to make it available in the next update ASAP.

Thanks.

**Comment by lil-peener** [comment]
thanks so much sent you a message on Reddit about the same thing.

**Comment by Jupiter79** [comment]
Please implement that :D

**Comment by elmoiv** [comment]
## In Progress... 👨🏻‍💻
![image](https://user-images.githubusercontent.com/31712173/155371579-3caad8ee-a90e-45ed-ab90-5e9893391b1b.png)
@LuanHimmlisch @lil-peener @Jupiter79

**Comment by elmoiv** [comment]
## In Progress... 👨🏻‍💻
![image](https://user-images.githubusercontent.com/31712173/155372155-5627a20e-6bab-49d4-94c1-b666eeaa6a8e.png)
@LuanHimmlisch @lil-peener @Jupiter79

**Comment by Jupiter79** [comment]
Btw @elmoiv could you possibly add an option to sort the nicknamed devices that they are at the top? Or highlight them like orange or pink?

**Comment by elmoiv** [comment]
I think it's better to add these in later updates. I am currently working on other projects and don't want to delay elmoCut 1.0.6 more :)

**Comment by elmoiv** [comment]
### elmoCut 1.0.6 is live now!
[![Download elmocut](https://a.fsdn.com/con/app/sf-download-button)](https://sourceforge.net/projects/elmocut/files/1.0.6/elmoCut.1.0.6.x64.exe/download)
