### ISSUE TITLE
[Suggestion] Add the ability to retrieve hostnames

### ISSUE THREAD

**Issue by Jupiter79** [elmoiv/elmocut#25]
Hey I think it would be nice and easy to implement for you to add the name of the device to the list so it is easier to associate the device with someone/something.

Like in netcut you can easily see the name of a the devices!

**Comment by elmoiv** [comment]
Can you describe your request clearly. I can't get what you mean by "add the name of the device to the list"

It would be great if you can add visualization of your description.

**Comment by Jupiter79** [comment]
I mean that it shows the Hostname of a device.

Like here the HP842AFD......
![Screenshot_6](https://user-images.githubusercontent.com/94369932/155540699-90578c4a-120a-475b-84c6-f81b98c1e546.png)

**Comment by elmoiv** [comment]
I will ad this to my TODO
