### ISSUE TITLE
Not detecting any devices

### ISSUE THREAD

**Issue by trololololD** [elmoiv/elmocut#27]
![sshot-2022-02-25-18-10-28](https://user-images.githubusercontent.com/53992008/155697041-f80eaef2-c6df-4944-b488-23b153aa97fe.png)

**Comment by elmoiv** [comment]
Try any of the following:
- Set system language to English
- Change Wi-Fi interface from elmoCut settings
- Disable any proxy or VPN and try again

Let me know if you still have the problem or got it fixed.

**Comment by trololololD** [comment]
i did all of 3 that u said but its still not fixed
im on windows 8.1

**Comment by trololololD** [comment]
hey its fixed now, i fixed it by uninstalling "Microsoft Hosted Network Virtual Adapter" and "Microsoft ISATAP Adapter" then scanned for hardware changes
