### ISSUE TITLE
elmocut cant define iphones vendor

### ISSUE THREAD

**Issue by FlaredMender683** [elmoiv/elmocut#29]
when I arp the network, I see some devices have the vendor as "none", they are actually Iphones and elmocut is not identifying its brand, please fix this issue. (it might be happening the same to samsung phones but I am not sure.)

**Comment by FlaredMender683** [comment]
![image](https://user-images.githubusercontent.com/103317237/162574071-7420c2e9-c7e3-4f4a-ba5a-c2992850852f.png)
you see the vendor after the mac address, but with Iphone devices you don't see it. That's what I am trying to say if you're gonna ask :)

**Comment by elmoiv** [comment]
Hey @FlaredMender683 ,

This has nothing to do with elmoCut.
The database storing devices MAC vendors has not been updated with this one. It may take some time to update your device and it depends on Wireshark database.

I searched the MAC you've attached and it doesn't exist
https://macaddress.io/mac-address-lookup/8L2oLj8A5E
https://aruljohn.com/mac/BABD0B
