### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by KiraiEEE** [elmoiv/elmocut#3]
First , I loved that software so much since SelfishNet & Netcut are worst thing to choose and the only one that really works is TuxCut which doesn't work on windows until i saw that one , its design so big but its somewhat gives an impressive aroma and hope it get more prosperity 
but i noticed some problems here : 
 1st : it doesnt show all devices with arp scan but after clicking ping scan the device starts glitching and lagging even background music start glitching and mouse cant move smoothly even thought it shows all devices 
 2nd : i hope u add an option to add ip adress or mac adress 
 3rd : the design is so big and can fit more with smaller buttons since its theme skin is so great
 4th : thank u for reading and for making the tool .
Can't wait until u do complete the TODO
good luck ♥ I hope I can support u cuz this one is literally POG

**Comment by elmoiv** [comment]
Hey @KiraiEEE ,
Happy you liked my work :)

1- ARP Scan is not always accurate (That's why I did created the Ping scan).
It looks like your machine lags while doing ping scan due to the large amount of threads running in the background. I will be ading more options like "single threaded scan" or an automatic thread handling according to CPU capabilities.

2- Okay, I will try to implement this feature ;)

3- Will be adjusting the design and themes more, since it's the first version and it surely has a lot to do.

4- You're welcome :)

I just postponed working on this project till I finish my final exams.

**Comment by elmoiv** [comment]
@vittojf 

Can you please execute this command in your shell and send me the output:

```
ipconfig
```

**Comment by vittojf** [comment]
`Radmin VPN Ethernet Adapter:

   Specific DNS suffix for the connection. . :
   IPv6 address. . . . . . . . . . : fdfd :: 1a99: 1863
   Link: local IPv6 address. . . : fe80 :: 58e: cd71: 82f6: bfb4% 7
   IPv4 address. . . . . . . . . . . . . . : 26.153.24.99
   Subnet mask . . . . . . . . . . . . : 255.0.0.0
   Default Gateway . . . . . : 26.0.0.1

Ethernet Npcap Loopback Adapter:

   Specific DNS suffix for the connection. . :
   Link: local IPv6 address. . . : fe80 :: f546: 1dd5: 2f86: 8e2e% 50
   Automatic configuration IPv4 address: 169.254.142.46
   Subnet mask . . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . :

Wireless LAN adapter Local Area Connection * 10:

   State of the media. . . . . . . . . . . : media disconnected
   Specific DNS suffix for the connection. . :

Wi-Fi wireless LAN adapter:

   Specific DNS suffix for the connection. . :
   Link: local IPv6 address. . . : fe80 :: 895e: f825: ead5: e030% 16
   IPv4 address. . . . . . . . . . . . . . : 192.168.1.103
   Subnet mask . . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . : 192.168.1.1

Wireless LAN adapter Local Area Connection * 9:

   State of the media. . . . . . . . . . . : media disconnected
   Specific DNS suffix for the connection. . :

Teredo Tunneling Pseudo-Interface Tunnel Adapter:

   Specific DNS suffix for the connection. . :
   IPv6 address. . . . . . . . . . : 2001: 0: 2841: f634: 387b: 1438: 4171: 20c3
   Link: local IPv6 address. . . : fe80 :: 387b: 1438: 4171: 20c3% 13
   Default Gateway . . . . . : `

**Comment by elmoiv** [comment]
I will try to fix this issue tomorrow cuz I am busy right now.

Thanks for your contribution :)

**Comment by vittojf** [comment]
Ok! :smiley:

**Comment by elmoiv** [comment]
Hey @vittojf ,

Can you try this patched version:

https://github.com/elmoiv/elmocut/blob/89781d5a0d333f2987d7eeb6ce58b59694929e80/data/elmocut.exe?raw=true

Please confirm if you got your bug fixed or still have any issues :)

**Comment by vittojf** [comment]
Thanks!!! <3  my problem was solved

**Comment by elmoiv** [comment]
@KiraiEEE 

elmoCut 1.0.4 has been released with a new feature to control running threads.
I think this may fix the glitching issue and make the scanner more stable.

**Comment by KiraiEEE** [comment]
> @KiraiEEE 
> 
> elmoCut 1.0.4 has been released with a new feature to control running threads.
> I think this may fix the glitching issue and make the scanner more stable.

❤️❤️❤️❤️

**Comment by KiraiEEE** [comment]
> @KiraiEEE 
> 
> elmoCut 1.0.4 has been released with a new feature to control running threads.
> I think this may fix the glitching issue and make the scanner more stable.

Btw after changing device the issue didnt happen again sorry i forgot to report it that my older one was low end but the new one is okay , but now the pinging scan became slower than before , so i think it would be better if u make the use of cores depends on the device running on or as an option in settings 
And thx 😉

**Comment by elmoiv** [comment]
I intentionally made it manual so that people can customize it as they want.

In many scenarios people will be running many applications that will be using most of the cores when elmocut is running. So, each user will be able to choose his sweet spot.

For you you can adjust it so that you can get it as your previous speed or faster.
