### ISSUE TITLE
Not all the internet users are scanned

### ISSUE THREAD

**Issue by DJoker21** [elmoiv/elmocut#30]
Even on a pinging scan,not all the users are seen, as in case of net cut or selfish net.Please fix the bug developer !!!!Thanks in advance!

**Comment by elmoiv** [comment]
Hey @DJoker21,

Device discovery is limited by default in elmoCut. You can adjust device count from settings as well as the running threads.

Please do as above and inform me with the result.

P.S:
elmoCut supports 255.255.255.0 subnet masks at the moment, meaning if your gateway is e.g. 192.168.1.1 and there is a device like 192.168.22.5, it won't be discoverable.

**Comment by elmoiv** [comment]
Closed for inactivity. Feel free to re-open the issue for any future help.
