### ISSUE TITLE
Not detecting any devices

### ISSUE THREAD

**Issue by roobini-gamer** [elmoiv/elmocut#32]
**description of the bug**
Elmocut is not detecting any other device other than my own PC and router
thing i tried to do : 
-re install elmocut and Npcap 
-run software as Admin
-joining different networks 
-updating/re installing all network drivers

**Screenshots**

![Capture-1](https://user-images.githubusercontent.com/69848832/165863968-76f21ebb-5486-4614-a01e-114f9dc64718.PNG)
![Capture-2](https://user-images.githubusercontent.com/69848832/165863969-fceaee7f-0486-4f07-983a-a09aeb8f33ce.PNG)
![Capture-3](https://user-images.githubusercontent.com/69848832/165863964-069a273f-d394-44f5-a03b-0da42c72c763.PNG)

**Desktop**
 - OS: fresh install&old Windows 10 pro
 - Browser chrome firefox edge
 - Version elmocut 1.0.6
 - wireless card: Tplink TL-WN722N v1 (Atheros chipset)

**Comment by elmoiv** [comment]
Please send the output of this command (In Powershell):
```arp -a```

**Comment by roobini-gamer** [comment]
> 
![Capture-4](https://user-images.githubusercontent.com/69848832/165997779-43ae835f-46e9-4c8e-aaee-a14c06bbf5d3.PNG)

**Comment by elmoiv** [comment]
The output is showing that your device is only detecting Router (Gateway) and your device. You may try to run Ping Scan from elmoCut then try and see the `arp -a` results again.

If they are the same then the problem is at your side and may be related to your:
- WiFi or Lan adapter.
- Network configuration.
- Router settings (Static ARP is enabled)

I would be thankful if you provided more information about your issue.

**Comment by amine234** [comment]
I have the same issue and couldn't fix it .
Please help

**Comment by roobini-gamer** [comment]
result of running the command `arp -a` after Ping Scan are the same as before this probably Wireless adapter issue i tried joining different networks but no positive result if i got my hand on another adapter im going to test it again

**Comment by elmoiv** [comment]
Okay. I leave this issue open until then.

Btw, you can try netcut or selfish net and see if the devices are discoverable or not.

**Comment by roobini-gamer** [comment]
> Okay. I leave this issue open until then.
> 
> Btw, you can try netcut or selfish net and see if the devices are discoverable or not.

yes netcut works fine but im not fan of it and them people behind it

**Comment by elmoiv** [comment]
That's why I made this peoject as open-source.

As time goes, elmoCut will evolve and all these issues will get solved.

**Comment by elmoiv** [comment]
@roobini-gamer 
@amine234 

Can you increase both device abd threads count from settings and try again?

**Comment by roobini-gamer** [comment]
> 

some how worked now without changing device count or threads
![Capture](https://user-images.githubusercontent.com/69848832/167918078-e406312b-a0b8-4d11-821b-f22f7f0f4d77.PNG)

**Comment by elmoiv** [comment]
At this point, this is related to your adapter or you didn't have any users on your network previously.

Increasing devices count will help discover devices that use longer IP address like 192.168.1.200 and so.

This issue is solved for now. If you have any problem in the future, feel free to re-open it.

**Comment by moisesmabu** [comment]
I have the same problem I still can't solve it.

**Comment by elmoiv** [comment]
Can you provide me with the following info in order to help you:
- Do you use external WiFi adapter or a built-in one?
- Open elmoCut Settings and send me a screenshot of your current config.
- What is your current Windows version and language?

**Comment by moisesmabu** [comment]
Do you use external WiFi adapter or a built-in one?
R = YES
What is your current Windows version and language?
R = Window 7 professional Spanish 
Open elmoCut Settings and send me a screenshot of your current config.
![123123](https://user-images.githubusercontent.com/113298344/189748898-9e121bc2-a33f-4daf-b015-77c4ff554a5a.JPG)

**Comment by elmoiv** [comment]
@moisesmabu 
Languages other than English are a current limitation of elmoCut. You can read them here:
https://github.com/elmoiv/elmocut#limitations

Please change your system language to English.

**Comment by moisesmabu** [comment]
- Do you use external WiFi adapter or a built-in one?
   - R = YES
   - What is your current Windows version and language?
   - R = Window 7 professional Spanish
   - Open elmoCut Settings and send me a screenshot of your current config.
