### ISSUE TITLE
doesn't show all devices 

### ISSUE THREAD

**Issue by lil-peener** [elmoiv/elmocut#34]
when I press the arping scan it will sometimes show 3 devices then I press it again and it will show more or less devices knowing that there are no devices disconnecting from the network. and when I press the pining scan it will show many fewer devices than the aping scan I don't know if the later is fixable or some devices just don't respond to pings. note i just increased the amount of threads allowed and this fixed the later problem but not the former

**Comment by elmoiv** [comment]
The Arping scan is for fast check and can't show all devices every time.

The pinging scan can show all devices but it's limited from settings so you can increase devices number according to your network and this will show all devices but scan will be slower.
