### ISSUE TITLE
[VcRedist] elmocut.py line 2 Can not load module

### ISSUE THREAD

**Issue by EijiHoba** [elmoiv/elmocut#38]
**Describe the bug**

elmoCut show an error message "elmocut.py line 2 Can not load module"

**To Reproduce**
1. run elmucut 
2. See error

**Expected behavior**
see main windows of elmocut

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1
 - Browser Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elmoiv** [comment]
I can't help without explaining your problem well.

Please do the following in order to help you:
- Clarify If you're using executable or running from source.
- Add screenshot or complete log of the error.

**Comment by Debuggerz1** [comment]
Same issue, switched to 1.0.5 and that one works fine, before a computer reset 1.0.6 was working fine, now it says that a module on line 2 is missing or something, I assume I'm missing one of those c++ runtimes but i couldn't be bothered to figure out which one 
![image](https://user-images.githubusercontent.com/22945624/177213778-8d15665e-8254-472f-a144-fe175cdf553c.png)

**Comment by elmoiv** [comment]
I will embed c++ runtime dlls into the next update and inform you ASAP to test if it is solved

**Comment by elmoiv** [comment]
Visual C++ Redistributable has been added to [requirements](https://github.com/elmoiv/elmocut/edit/main/README.md#requirements):
> ## Requirements
>   - x64 Microsoft Windows >= 7
>   - .NET Framework 3+
>   - Visual C++ Redistributable Runtimes: [Download](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/)
>   - Npcap: [Download](https://nmap.org/npcap/dist/npcap-1.10.exe)
