### ISSUE TITLE
"Connection lost!"

### ISSUE THREAD

**Issue by MartiiDev** [elmoiv/elmocut#4]
Hello, I decided to try your software as I was tired of NetCut's ads or premium restrictions but when I launch ElmoCut a popup saying "Connection Lost!" appears. If I run an ARP scan or a ping scan the popup pops again and no devices are detected.

I have tried uninstalling NetCut, updating npCap, restarting my computer, reinstalling ElmoCut, but nothing seems to solve the problem.
I'm using the latest release of ElmoCut on Windows 10 21H1. I may have simply done something wrong though... Thanks in advance!

**Comment by elmoiv** [comment]
Hey @MartiiDev ,

Can you try this patched version:

https://github.com/elmoiv/elmocut/blob/89781d5a0d333f2987d7eeb6ce58b59694929e80/data/elmocut.exe?raw=true

You may run it via Windows Shell to catch any errors and send a copy here to understand your issue well.

Please confirm if you got your bug fixed or still have any issues :)

**Comment by MartiiDev** [comment]
Yay thanks, I replaced the .exe and everything works fine now. What did this new .exe change btw?
By the way how can I disable the shell opening when I launch ElmoCut with this new version?

And do you plan on adding a way to control how much you kill a device? I know netcut can half kill a device for exemple, so their internet is two times slower.

**Comment by elmoiv** [comment]
This EXE contains latest patches as a quick fix but will be opening with terminal for future errors.

Only Releases will have no shell.

I am trying to implement network speed control but it's somehow hard besides my free time is not that much lately.

I will try to contribute as much as I can :)
