### ISSUE TITLE
Can't run from source [Python 3.10]

### ISSUE THREAD

**Issue by KiraiEEE** [elmoiv/elmocut#42]
Hi Dev, thanks for the tasty software that i really love <3

i faced some issues during dealing with the sauce code : 

- 🎂 installing from requirements.txt had an issue with versions so i recommend changing the `==` to `>=`
- 🎂 i got problems with scapy.all 
![image](https://user-images.githubusercontent.com/54278089/193026169-f52c1720-0e47-4208-9f97-f420fd7f9a1f.png)
- 🎂 im having hard time understanding the code (i wanna help improving this project but im still learning) so if there is a plan or titles/todo or smthing that can help me learn about it please provide n i appreciate <33

again thx for the jucy software , have a nice day

**Comment by elmoiv** [comment]
You may try to downgrade python to 3.7 and try again

**Comment by KiraiEEE** [comment]
> You may try to downgrade python to 3.7 and try again

thank u for replying to **some** of my questions, hope u a guud day 🌸

**Comment by elmoiv** [comment]
Feel free to teat and report again. I will see if I can help you with your issue.

Don't worry if I didn't reply in time. I have a tight schedule these days. But I will answer sooner or later :)

**Comment by MrKuky** [comment]
Hello, I have the same problem. How did you fix it?

**Comment by elmoiv** [comment]
@MrKuky 
I only have Python 3.7 on my machine. Please downgrade to this version or upgrade if yours is lower than 3.7.x

**Comment by KiraiEEE** [comment]
> Hello, I have the same problem. How did you fix it?

i did downgrade to 3.7 but still facing errors so i cancelled sadly :')

**Comment by elmoiv** [comment]
> > Hello, I have the same problem. How did you fix it?
> 
> i did downgrade to 3.7 but still facing errors so i cancelled sadly :')

Please send a screenshot or log of the errors you're facing

**Comment by MrKuky** [comment]
I have 3.10 but as @KiraiEEE said it wont help probably.

![image](https://user-images.githubusercontent.com/34176329/199195599-d457011e-ec41-46ea-8b06-1112a859ae62.png)

**Comment by KiraiEEE** [comment]
> > > Hello, I have the same problem. How did you fix it?
> > 
> > i did downgrade to 3.7 but still facing errors so i cancelled sadly :')
> 
> Please send a screenshot or log of the errors you're facing

i upgraded my python environment and cancelled my to-dos, i was willing to add some great features but faced a lot of errors sadly

**Comment by elmoiv** [comment]
@MrKuky @KiraiEEE 
I want to help solve this issue but unfortunately, I will not be available in the next 3 months.

I will continue working on this project as of 01/02/2023

**Comment by KiraiEEE** [comment]
> @MrKuky @KiraiEEE 
> I want to help solve this issue but unfortunately, I will not be available in the next 3 months.
> 
> I will continue working on this project as of 01/02/2023

i will try in ma free tym too otherwise gonna wait for ya xd

good luck on wut u doin tho

**Comment by MrKuky** [comment]
Hello there again! So did anyone find solution? 😃

**Comment by KiraiEEE** [comment]
> Hey @MrKuky , Please:
> - Download and install Python 3.7.7 from here: 
> https://www.python.org/downloads/release/python-377/
> - Install requirements via:
> `pip install -r requirements.txt`
> 
> Then try to run from source using `RUN.bat` and tell me if there are any issues.

worked (add "requests" to the pip too)

thx <33
