### ISSUE TITLE
ERROR: No matching distribution found for pyqt5-tools==5.13.0.1.5

### ISSUE THREAD

**Issue by xvllinihao** [elmoiv/elmocut#5]
Hi elmoiv,

I am trying to pip install the requirements.txt, and meet this problem. I am using Python3.8, can you tell me the python version that you use?

Best,
Li

**Comment by elmoiv** [comment]
Python 3.7 64 bit

**Comment by elmoiv** [comment]
If you want to run elmocut from source, you don't have to install `pyqt5-tools`. 
It's only if you want to use GUI designer and other tools.

**Comment by xvllinihao** [comment]
> Python 3.7 64 bit

ok, thanks,
