### ISSUE TITLE
one detection from virustotal 

### ISSUE THREAD

**Issue by xJamayka** [elmoiv/elmocut#58]
virustotal detection 
![image](https://user-images.githubusercontent.com/12401827/228660096-a7aca8a3-4332-4762-9826-461c0fc86a14.png)

https://www.virustotal.com/gui/file/be913abdd50e0793c8ae8e8ec715cb214b8dab3af36b8c9c478562037e2289ca?nocache=1

**Comment by LethalAspect** [comment]
its a false positive

**Comment by elmoiv** [comment]
#55
