### ISSUE TITLE
The System cannot find the file specified: Failed to load script

### ISSUE THREAD

**Issue by waleed335** [elmoiv/elmocut#6]
![Untitled](https://user-images.githubusercontent.com/66493769/115062278-9d6fcc00-9f03-11eb-8218-87e39bd180e6.png)

**Comment by elmoiv** [comment]
I think this issue is related to your Windows version.

Try to turn off controlled folder access.

Here is a walkthrough on how to disable this option that may be preventing elmocut from writing to documents folder:
https://kb.acronis.com/content/62142
