### ISSUE TITLE
App Crashed second after being Launched

### ISSUE THREAD

**Issue by Shikitsuna** [elmoiv/elmocut#63]
I Tried before until i changing my adapter from abgn into 802.11 AC (if that's matters). When it launch seems like normal after it dissapeared/crashed without any notification on "ARPing your network" status

**Comment by Shikitsuna** [comment]
found out my NpCap also updated to newer version will crash this, stay at 1.10 NPcap

**Comment by elmoiv** [comment]
Will see if I can handle newer versions of npcap in future updates.
