### ISSUE TITLE
"Connection Lost"

### ISSUE THREAD

**Issue by volumika** [elmoiv/elmocut#67]
New to github. I saw the https://github.com/elmoiv/elmocut/issues/4 page but that's 2 years old and the solution listed there doesn't work anymore .

Just like the link listed above, I am welcomed with a Connection Lost dialog. This dialog persists with most connection related activities trying to be attempted. I cannot locate any devices.
Alongside that, I also attempted to reinstall my adapter's drivers, but to no avail.
![image](https://github.com/elmoiv/elmocut/assets/141886374/642b01e2-545e-474c-8400-b67310fbb49b)
![image](https://github.com/elmoiv/elmocut/assets/141886374/bf2a632a-b1d8-4f74-926c-67ada0ca7215)

Like the link above, I have restarted my laptop numerous times and tried reinstalling Npcap and Elmocut however no solution has been found in this regard.

Help would be appreciated, Thank you in advance!

Windows 7 Professional, HP Pavilion G6, Intel I3. Seems to be built in the factory in 2012, known via BIOS. Hopefully any of that can help.

**Comment by volumika** [comment]
Issue has been fixed.  I did this by installing the Npcap v1.31 drivers. located in the install of the v1.50 drivers. There should be a disclaimer informing people about this.
![image](https://github.com/elmoiv/elmocut/assets/141886374/0b9e8f75-d0b7-4c2c-86b0-30e29d68a46c)

**Comment by elmoiv** [comment]
Okay thank you!
