### ISSUE TITLE
unable to kill android devices

### ISSUE THREAD

**Issue by dunderelmo** [elmoiv/elmocut#7]
I was testing elmocut and tried to kill my android devices connected to my router, the app shows as killed but all the devices have internet connectivity, tried this on POCO M2 pro, MOTO G4plus,

**Comment by elmoiv** [comment]
It may be an adapter dependent issue or something with ARP protection in your Router.

Can you please send me the following information:
- You Windows version and build version.
- Your Adapter Information.
- NPCAP version.
- You router brand. 

Stick with the coming updates as I will be improving elmoCut over time and your issue may be solved.

**Comment by elmoiv** [comment]
Issue closed due to inactivity.

Feel free to re-open the issue if you have more info about your problem.
