### ISSUE TITLE
whenever i kill i myself get disconnected

### ISSUE THREAD

**Issue by Anmol-SlayerOP** [elmoiv/elmocut#72]
I am Connected to College's Wifi
whenever i kill any other(single or all the devices except mine) device i myself get blocked/disconnected for some like  5 minutes and then again can connect so what is the issue ?
also all other device vendor is Cisco and the router is also of Cisco
![image](https://github.com/elmoiv/elmocut/assets/119871703/2356d961-cc1e-4414-baf3-39659befcc2c)
So is there security or something which is preventing me to this
So can I kill Other connections or not i.e. is there fault in your app or none of the apps can work

**Comment by elmoiv** [comment]
From the screenshot you've attached. It seems like that there is a broadcasting device called cisco that is masking MAC addresses for all users using its own MAC address. Thus you can't block the internet connection of any one or you will block connection for everyone including you.
