### ISSUE TITLE
Trojan.Win32.CoinMiner

### ISSUE THREAD

**Issue by conansb3** [elmoiv/elmocut#77]
![Annotation 2024-12-10 004542](https://github.com/user-attachments/assets/fe6d09ed-67fc-49f1-bca9-4ede8cab1b0c)

**Comment by conansb3** [comment]
BE CAREFUL GUYS

**Comment by elmoiv** [comment]
#71

**Comment by conansb3** [comment]
can you explain?

**Comment by elmoiv** [comment]
The bootloader building mechanism can be mis-flagged by antivirus providers:

Read more on the PyInstaller issue:
https://github.com/pyinstaller/pyinstaller/issues/603
